# Generated by Django 4.1.2 on 2023-04-20 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('M', 'Monday'), ('TU', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday')], max_length=2)),
                ('weekday_iso', models.IntegerField(null=True)),
                ('start', models.CharField(max_length=8, null=True)),
                ('end', models.CharField(max_length=8, null=True)),
                ('grade_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.gradessubjects')),
            ],
            options={
                'db_table': 'schedule_table',
            },
        ),
    ]
