# Generated by Django 4.1.2 on 2023-04-25 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schedulesubjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesubjects',
            name='grade_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='schedules', to='school.gradessubjects'),
        )#,
        # migrations.AlterModelTable(
        #     name='schedulesubjects',
        #     table='schedule_subjects',
        # ),
    ]
