# Generated by Django 4.1.2 on 2023-04-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_schedulesubjects_table'),
    ]

    operations = [
       
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filelink', models.CharField(max_length=256)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='reports', to='school.children')),
                ('grade_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='reports', to='school.gradessubjects')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
